// Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/alarm/count": {
            "post": {
                "description": "查询报警",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alarm"
                ],
                "summary": "查询报警",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/alarm/list": {
            "get": {
                "description": "查询报警",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alarm"
                ],
                "summary": "查询报警",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Alarm"
                        }
                    }
                }
            }
        },
        "/alarm/search": {
            "post": {
                "description": "查询报警",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alarm"
                ],
                "summary": "查询报警",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Alarm"
                        }
                    }
                }
            }
        },
        "/alarm/{id}/delete": {
            "get": {
                "description": "删除报警",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alarm"
                ],
                "summary": "删除报警",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "报警ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Alarm"
                        }
                    }
                }
            }
        },
        "/alarm/{id}/read": {
            "get": {
                "description": "阅读报警",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "alarm"
                ],
                "summary": "阅读报警",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "报警ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Alarm"
                        }
                    }
                }
            }
        },
        "/validator/count": {
            "post": {
                "description": "查询检查数量",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "查询检查数量",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/validator/create": {
            "post": {
                "description": "创建检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "创建检查",
                "parameters": [
                    {
                        "description": "检查信息",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Validator"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Validator"
                        }
                    }
                }
            }
        },
        "/validator/export": {
            "get": {
                "description": "导出检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导出检查",
                "responses": {}
            }
        },
        "/validator/import": {
            "post": {
                "description": "导入检查",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "product"
                ],
                "summary": "导入检查",
                "parameters": [
                    {
                        "type": "file",
                        "description": "压缩包",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-int64"
                        }
                    }
                }
            }
        },
        "/validator/list": {
            "get": {
                "description": "查询检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "查询检查",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "skip",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Validator"
                        }
                    }
                }
            }
        },
        "/validator/search": {
            "post": {
                "description": "查询检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "查询检查",
                "parameters": [
                    {
                        "description": "查询参数",
                        "name": "search",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.ParamSearch"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyList-types_Validator"
                        }
                    }
                }
            }
        },
        "/validator/{id}": {
            "get": {
                "description": "获取检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "获取检查",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "检查ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Validator"
                        }
                    }
                }
            },
            "post": {
                "description": "修改检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "修改检查",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "检查ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "检查信息",
                        "name": "validator",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Validator"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Validator"
                        }
                    }
                }
            }
        },
        "/validator/{id}/delete": {
            "get": {
                "description": "删除检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "删除检查",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "检查ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Validator"
                        }
                    }
                }
            }
        },
        "/validator/{id}/disable": {
            "get": {
                "description": "禁用检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "禁用检查",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "检查ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Validator"
                        }
                    }
                }
            }
        },
        "/validator/{id}/enable": {
            "get": {
                "description": "启用检查",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "validator"
                ],
                "summary": "启用检查",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "检查ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ReplyData-types_Validator"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ParamSearch": {
            "type": "object",
            "properties": {
                "filter": {
                    "type": "object",
                    "additionalProperties": true
                },
                "keyword": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "limit": {
                    "type": "integer"
                },
                "skip": {
                    "type": "integer"
                },
                "sort": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.ReplyData-int64": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "integer"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Alarm": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Alarm"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyData-types_Validator": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/types.Validator"
                },
                "error": {
                    "type": "string"
                }
            }
        },
        "api.ReplyList-types_Alarm": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Alarm"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.ReplyList-types_Validator": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/types.Validator"
                    }
                },
                "error": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "types.Alarm": {
            "type": "object",
            "properties": {
                "created": {
                    "type": "string"
                },
                "device_id": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "read": {
                    "type": "boolean"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "types.Validator": {
            "type": "object",
            "properties": {
                "again": {
                    "description": "再次提醒间隔s",
                    "type": "integer"
                },
                "created": {
                    "type": "string"
                },
                "delay": {
                    "description": "延迟时间s",
                    "type": "integer"
                },
                "disabled": {
                    "type": "boolean"
                },
                "expression": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "product_id": {
                    "type": "string"
                },
                "template": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "total": {
                    "description": "总提醒次数",
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0 版本",
	Host:             "",
	BasePath:         "/app/alarm/api/",
	Schemes:          []string{},
	Title:            "历史数据接口文档",
	Description:      "API文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
